#Product Name: Simple Sales Center (Castor Enterprise)
#Written By: David Zhang, Jason Lam, Jeff Jun, Phillip Lee
#To be Submitted to: Ms. Wun
#Date: February 4, 2013
#Purpose: Output all the graphic user interface of human resources program to the user and allow them to interact with supported functions

from Main import*
from Associate import*
from finalSearchWindow import*
from PyQt4 import QtCore, QtGui
ReadFile()
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimpleSaleCenterMainWindow(object):
    def setupUi(self, SimpleSaleCenterMainWindow):
        SimpleSaleCenterMainWindow.setObjectName(_fromUtf8("SimpleSaleCenterMainWindow"))
        SimpleSaleCenterMainWindow.resize(835, 575)
        self.centralwidget = QtGui.QWidget(SimpleSaleCenterMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 251, 411))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.listLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.listLayout.setMargin(0)
        self.listLayout.setObjectName(_fromUtf8("listLayout"))
        self.listTitle = QtGui.QPushButton(self.verticalLayoutWidget)
        self.listTitle.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.listTitle.setPalette(palette)
        self.listTitle.setObjectName(_fromUtf8("listTitle"))
        self.listLayout.addWidget(self.listTitle)
        self.employeeTable = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.employeeTable.setObjectName(_fromUtf8("employeeTable"))
        self.employeeTable.setColumnCount(2)
        self.employeeTable.setRowCount(100)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(31, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(32, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(33, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(34, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(35, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(36, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(37, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(38, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(39, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(40, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(41, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(42, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(43, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(44, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(45, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(46, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(47, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(48, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(49, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(50, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(51, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(52, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(53, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(54, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(55, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(56, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(57, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(58, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(59, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(60, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(61, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(62, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(63, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(64, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(65, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(66, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(67, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(68, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(69, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(70, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(71, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(72, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(73, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(74, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(75, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(76, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(77, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(78, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(79, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(80, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(81, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(82, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(83, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(84, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(85, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(86, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(87, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(88, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(89, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(90, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(91, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(92, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(93, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(94, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(95, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(96, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(97, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(98, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setVerticalHeaderItem(99, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.employeeTable.setHorizontalHeaderItem(1, item)
        self.listLayout.addWidget(self.employeeTable)
        self.mainTitle = QtGui.QLabel(self.centralwidget)
        self.mainTitle.setGeometry(QtCore.QRect(10, 10, 461, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(36)
        font.setItalic(False)
        font.setUnderline(False)
        self.mainTitle.setFont(font)
        self.mainTitle.setObjectName(_fromUtf8("mainTitle"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(270, 70, 561, 461))
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.lNameText = QtGui.QPlainTextEdit(self.generalTab)
        self.lNameText.setGeometry(QtCore.QRect(320, 10, 131, 31))
        self.lNameText.setObjectName(_fromUtf8("lNameText"))
        self.genderLabel = QtGui.QLabel(self.generalTab)
        self.genderLabel.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.cellPhoneLabel = QtGui.QLabel(self.generalTab)
        self.cellPhoneLabel.setGeometry(QtCore.QRect(20, 360, 81, 16))
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.lNameLab = QtGui.QLabel(self.generalTab)
        self.lNameLab.setGeometry(QtCore.QRect(250, 20, 71, 16))
        self.lNameLab.setObjectName(_fromUtf8("lNameLab"))
        self.homePhoneText = QtGui.QPlainTextEdit(self.generalTab)
        self.homePhoneText.setGeometry(QtCore.QRect(100, 320, 131, 31))
        self.homePhoneText.setObjectName(_fromUtf8("homePhoneText"))
        self.homePhoneLabel = QtGui.QLabel(self.generalTab)
        self.homePhoneLabel.setGeometry(QtCore.QRect(20, 320, 81, 16))
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.marriedBox = QtGui.QComboBox(self.generalTab)
        self.marriedBox.setGeometry(QtCore.QRect(390, 60, 81, 22))
        self.marriedBox.setObjectName(_fromUtf8("marriedBox"))
        self.marriedBox.addItem(_fromUtf8(""))
        self.marriedBox.addItem(_fromUtf8(""))
        self.marriedBox.addItem(_fromUtf8(""))
        self.fNameText = QtGui.QPlainTextEdit(self.generalTab)
        self.fNameText.setGeometry(QtCore.QRect(90, 10, 131, 31))
        self.fNameText.setPlainText(_fromUtf8(""))
        self.fNameText.setObjectName(_fromUtf8("fNameText"))
        self.cancelButton = QtGui.QPushButton(self.generalTab)
        self.cancelButton.setGeometry(QtCore.QRect(330, 400, 75, 23))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.addressLabel = QtGui.QLabel(self.generalTab)
        self.addressLabel.setGeometry(QtCore.QRect(20, 250, 61, 16))
        self.addressLabel.setObjectName(_fromUtf8("addressLabel"))
        self.startDateText = QtGui.QPlainTextEdit(self.generalTab)
        self.startDateText.setGeometry(QtCore.QRect(330, 280, 121, 31))
        self.startDateText.setObjectName(_fromUtf8("startDateText"))
        self.degreeBox = QtGui.QComboBox(self.generalTab)
        self.degreeBox.setGeometry(QtCore.QRect(90, 280, 131, 22))
        self.degreeBox.setObjectName(_fromUtf8("degreeBox"))
        self.degreeBox.addItem(_fromUtf8(""))
        self.degreeBox.addItem(_fromUtf8(""))
        self.degreeBox.addItem(_fromUtf8(""))
        self.degreeBox.addItem(_fromUtf8(""))
        self.startDateLabel = QtGui.QLabel(self.generalTab)
        self.startDateLabel.setGeometry(QtCore.QRect(230, 280, 91, 16))
        self.startDateLabel.setObjectName(_fromUtf8("startDateLabel"))
        self.idLabel = QtGui.QLabel(self.generalTab)
        self.idLabel.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.managerLabel = QtGui.QLabel(self.generalTab)
        self.managerLabel.setGeometry(QtCore.QRect(20, 210, 101, 16))
        self.managerLabel.setObjectName(_fromUtf8("managerLabel"))
        self.departText = QtGui.QPlainTextEdit(self.generalTab)
        self.departText.setGeometry(QtCore.QRect(100, 160, 121, 31))
        self.departText.setObjectName(_fromUtf8("departText"))
        self.marriedLabel = QtGui.QLabel(self.generalTab)
        self.marriedLabel.setGeometry(QtCore.QRect(300, 60, 91, 16))
        self.marriedLabel.setObjectName(_fromUtf8("marriedLabel"))
        self.sinLabel = QtGui.QLabel(self.generalTab)
        self.sinLabel.setGeometry(QtCore.QRect(250, 130, 41, 16))
        self.sinLabel.setObjectName(_fromUtf8("sinLabel"))
        self.idText = QtGui.QPlainTextEdit(self.generalTab)
        self.idText.setGeometry(QtCore.QRect(110, 120, 121, 31))
        self.idText.setObjectName(_fromUtf8("idText"))
        self.bDateText = QtGui.QPlainTextEdit(self.generalTab)
        self.bDateText.setGeometry(QtCore.QRect(190, 80, 171, 31))
        self.bDateText.setPlainText(_fromUtf8(""))
        self.bDateText.setObjectName(_fromUtf8("bDateText"))
        self.jobLabel = QtGui.QLabel(self.generalTab)
        self.jobLabel.setGeometry(QtCore.QRect(240, 170, 81, 16))
        self.jobLabel.setObjectName(_fromUtf8("jobLabel"))
        self.sinText = QtGui.QPlainTextEdit(self.generalTab)
        self.sinText.setGeometry(QtCore.QRect(300, 120, 121, 31))
        self.sinText.setObjectName(_fromUtf8("sinText"))
        self.jobText = QtGui.QPlainTextEdit(self.generalTab)
        self.jobText.setGeometry(QtCore.QRect(320, 160, 121, 31))
        self.jobText.setObjectName(_fromUtf8("jobText"))
        self.managerText = QtGui.QPlainTextEdit(self.generalTab)
        self.managerText.setGeometry(QtCore.QRect(120, 200, 181, 31))
        self.managerText.setObjectName(_fromUtf8("managerText"))
        self.addressText = QtGui.QPlainTextEdit(self.generalTab)
        self.addressText.setGeometry(QtCore.QRect(100, 240, 371, 31))
        self.addressText.setObjectName(_fromUtf8("addressText"))
        self.genderF = QtGui.QRadioButton(self.generalTab)
        self.genderF.setGeometry(QtCore.QRect(140, 60, 90, 16))
        self.genderF.setChecked(False)
        self.genderF.setAutoRepeat(True)
        self.genderF.setObjectName(_fromUtf8("genderF"))
        self.emailLabel = QtGui.QLabel(self.generalTab)
        self.emailLabel.setGeometry(QtCore.QRect(240, 360, 81, 16))
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.emailText = QtGui.QPlainTextEdit(self.generalTab)
        self.emailText.setGeometry(QtCore.QRect(280, 360, 191, 31))
        self.emailText.setObjectName(_fromUtf8("emailText"))
        self.workPhoneText = QtGui.QPlainTextEdit(self.generalTab)
        self.workPhoneText.setGeometry(QtCore.QRect(330, 320, 131, 31))
        self.workPhoneText.setObjectName(_fromUtf8("workPhoneText"))
        self.departLabel = QtGui.QLabel(self.generalTab)
        self.departLabel.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.departLabel.setObjectName(_fromUtf8("departLabel"))
        self.fNameLabel = QtGui.QLabel(self.generalTab)
        self.fNameLabel.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.fNameLabel.setObjectName(_fromUtf8("fNameLabel"))
        self.genderO = QtGui.QRadioButton(self.generalTab)
        self.genderO.setGeometry(QtCore.QRect(220, 60, 90, 16))
        self.genderO.setChecked(False)
        self.genderO.setAutoRepeat(True)
        self.genderO.setObjectName(_fromUtf8("genderO"))
        self.cellPhoneText = QtGui.QPlainTextEdit(self.generalTab)
        self.cellPhoneText.setGeometry(QtCore.QRect(90, 360, 131, 31))
        self.cellPhoneText.setObjectName(_fromUtf8("cellPhoneText"))
        self.genderM = QtGui.QRadioButton(self.generalTab)
        self.genderM.setGeometry(QtCore.QRect(70, 60, 90, 16))
        self.genderM.setChecked(False)
        self.genderM.setAutoRepeat(True)
        self.genderM.setObjectName(_fromUtf8("genderM"))
        self.bDateLabel = QtGui.QLabel(self.generalTab)
        self.bDateLabel.setGeometry(QtCore.QRect(20, 90, 161, 16))
        self.bDateLabel.setObjectName(_fromUtf8("bDateLabel"))
        self.degreeLabel = QtGui.QLabel(self.generalTab)
        self.degreeLabel.setGeometry(QtCore.QRect(20, 280, 71, 16))
        self.degreeLabel.setObjectName(_fromUtf8("degreeLabel"))
        self.workPhoneLabel = QtGui.QLabel(self.generalTab)
        self.workPhoneLabel.setGeometry(QtCore.QRect(240, 320, 81, 16))
        self.workPhoneLabel.setObjectName(_fromUtf8("workPhoneLabel"))
        self.editButton = QtGui.QPushButton(self.generalTab)
        self.editButton.setGeometry(QtCore.QRect(130, 400, 75, 23))
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.updateButton = QtGui.QPushButton(self.generalTab)
        self.updateButton.setGeometry(QtCore.QRect(230, 400, 75, 23))
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.salaryPayRateLabel = QtGui.QLabel(self.generalTab)
        self.salaryPayRateLabel.setGeometry(QtCore.QRect(310, 210, 91, 16))
        self.salaryPayRateLabel.setObjectName(_fromUtf8("salaryPayRateLabel"))
        self.salaryPayRateText = QtGui.QPlainTextEdit(self.generalTab)
        self.salaryPayRateText.setGeometry(QtCore.QRect(400, 200, 111, 31))
        self.salaryPayRateText.setObjectName(_fromUtf8("salaryPayRateText"))
        self.tabs.addTab(self.generalTab, _fromUtf8(""))
        self.attendanceTab = QtGui.QWidget()
        self.attendanceTab.setObjectName(_fromUtf8("attendanceTab"))
        self.workedDaysLabel = QtGui.QLabel(self.attendanceTab)
        self.workedDaysLabel.setGeometry(QtCore.QRect(150, 90, 81, 16))
        self.workedDaysLabel.setObjectName(_fromUtf8("workedDaysLabel"))
        self.sickDaysLabel = QtGui.QLabel(self.attendanceTab)
        self.sickDaysLabel.setGeometry(QtCore.QRect(150, 210, 71, 16))
        self.sickDaysLabel.setObjectName(_fromUtf8("sickDaysLabel"))
        self.vacationLabel = QtGui.QLabel(self.attendanceTab)
        self.vacationLabel.setGeometry(QtCore.QRect(150, 270, 101, 16))
        self.vacationLabel.setObjectName(_fromUtf8("vacationLabel"))
        self.workedDaysPButton = QtGui.QPushButton(self.attendanceTab)
        self.workedDaysPButton.setGeometry(QtCore.QRect(340, 80, 21, 23))
        self.workedDaysPButton.setObjectName(_fromUtf8("workedDaysPButton"))
        self.workedDaysMButton = QtGui.QPushButton(self.attendanceTab)
        self.workedDaysMButton.setGeometry(QtCore.QRect(370, 80, 21, 23))
        self.workedDaysMButton.setObjectName(_fromUtf8("workedDaysMButton"))
        self.workedDaysText = QtGui.QPlainTextEdit(self.attendanceTab)
        self.workedDaysText.setGeometry(QtCore.QRect(240, 80, 91, 31))
        self.workedDaysText.setObjectName(_fromUtf8("workedDaysText"))
        self.sickDaysText = QtGui.QPlainTextEdit(self.attendanceTab)
        self.sickDaysText.setGeometry(QtCore.QRect(220, 200, 91, 31))
        self.sickDaysText.setObjectName(_fromUtf8("sickDaysText"))
        self.sickDaysPButton = QtGui.QPushButton(self.attendanceTab)
        self.sickDaysPButton.setGeometry(QtCore.QRect(320, 200, 21, 23))
        self.sickDaysPButton.setObjectName(_fromUtf8("sickDaysPButton"))
        self.sickDaysMButton = QtGui.QPushButton(self.attendanceTab)
        self.sickDaysMButton.setGeometry(QtCore.QRect(350, 200, 21, 23))
        self.sickDaysMButton.setObjectName(_fromUtf8("sickDaysMButton"))
        self.vacationPButton = QtGui.QPushButton(self.attendanceTab)
        self.vacationPButton.setGeometry(QtCore.QRect(340, 260, 21, 23))
        self.vacationPButton.setObjectName(_fromUtf8("vacationPButton"))
        self.vacationMButton = QtGui.QPushButton(self.attendanceTab)
        self.vacationMButton.setGeometry(QtCore.QRect(370, 260, 21, 23))
        self.vacationMButton.setObjectName(_fromUtf8("vacationMButton"))
        self.vacationText = QtGui.QPlainTextEdit(self.attendanceTab)
        self.vacationText.setGeometry(QtCore.QRect(240, 260, 91, 31))
        self.vacationText.setObjectName(_fromUtf8("vacationText"))
        self.availableVacationLabel = QtGui.QLabel(self.attendanceTab)
        self.availableVacationLabel.setGeometry(QtCore.QRect(150, 320, 161, 16))
        self.availableVacationLabel.setObjectName(_fromUtf8("availableVacationLabel"))
        self.availableVacationText = QtGui.QPlainTextEdit(self.attendanceTab)
        self.availableVacationText.setGeometry(QtCore.QRect(310, 310, 91, 31))
        self.availableVacationText.setObjectName(_fromUtf8("availableVacationText"))
        self.overWorkPButton = QtGui.QPushButton(self.attendanceTab)
        self.overWorkPButton.setGeometry(QtCore.QRect(370, 140, 21, 23))
        self.overWorkPButton.setObjectName(_fromUtf8("overWorkPButton"))
        self.overWorkLabel = QtGui.QLabel(self.attendanceTab)
        self.overWorkLabel.setGeometry(QtCore.QRect(150, 150, 151, 16))
        self.overWorkLabel.setObjectName(_fromUtf8("overWorkLabel"))
        self.overWorkText = QtGui.QPlainTextEdit(self.attendanceTab)
        self.overWorkText.setGeometry(QtCore.QRect(290, 140, 71, 31))
        self.overWorkText.setObjectName(_fromUtf8("overWorkText"))
        self.overWorkMButton = QtGui.QPushButton(self.attendanceTab)
        self.overWorkMButton.setGeometry(QtCore.QRect(400, 140, 21, 23))
        self.overWorkMButton.setObjectName(_fromUtf8("overWorkMButton"))
        self.tabs.addTab(self.attendanceTab, _fromUtf8(""))
        self.payrollTab = QtGui.QWidget()
        self.payrollTab.setObjectName(_fromUtf8("payrollTab"))
        self.generalPayLabel = QtGui.QLabel(self.payrollTab)
        self.generalPayLabel.setGeometry(QtCore.QRect(120, 130, 101, 21))
        self.generalPayLabel.setObjectName(_fromUtf8("generalPayLabel"))
        self.bonusLabel = QtGui.QLabel(self.payrollTab)
        self.bonusLabel.setGeometry(QtCore.QRect(310, 130, 41, 21))
        self.bonusLabel.setObjectName(_fromUtf8("bonusLabel"))
        self.deductionLabel = QtGui.QLabel(self.payrollTab)
        self.deductionLabel.setGeometry(QtCore.QRect(410, 130, 101, 21))
        self.deductionLabel.setObjectName(_fromUtf8("deductionLabel"))
        self.generalPayText = QtGui.QPlainTextEdit(self.payrollTab)
        self.generalPayText.setGeometry(QtCore.QRect(80, 150, 141, 31))
        self.generalPayText.setObjectName(_fromUtf8("generalPayText"))
        self.bonusText = QtGui.QPlainTextEdit(self.payrollTab)
        self.bonusText.setGeometry(QtCore.QRect(310, 150, 61, 31))
        self.bonusText.setObjectName(_fromUtf8("bonusText"))
        self.deductionText = QtGui.QPlainTextEdit(self.payrollTab)
        self.deductionText.setGeometry(QtCore.QRect(410, 150, 61, 31))
        self.deductionText.setObjectName(_fromUtf8("deductionText"))
        self.money_1 = QtGui.QLabel(self.payrollTab)
        self.money_1.setGeometry(QtCore.QRect(70, 150, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.money_1.setFont(font)
        self.money_1.setObjectName(_fromUtf8("money_1"))
        self.money_3 = QtGui.QLabel(self.payrollTab)
        self.money_3.setGeometry(QtCore.QRect(300, 150, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.money_3.setFont(font)
        self.money_3.setObjectName(_fromUtf8("money_3"))
        self.money_4 = QtGui.QLabel(self.payrollTab)
        self.money_4.setGeometry(QtCore.QRect(400, 150, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.money_4.setFont(font)
        self.money_4.setObjectName(_fromUtf8("money_4"))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.totalSign = QtGui.QLabel(self.payrollTab)
        self.totalSign.setGeometry(QtCore.QRect(60, 220, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalSign.setFont(font)
        self.totalSign.setObjectName(_fromUtf8("totalSign"))


        font = QtGui.QFont()
        font.setPointSize(12)

        self.operation_2 = QtGui.QLabel(self.payrollTab)
        self.operation_2.setGeometry(QtCore.QRect(255, 150, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operation_2.setFont(font)
        self.operation_2.setObjectName(_fromUtf8("operation_2"))
        self.operation_3 = QtGui.QLabel(self.payrollTab)
        self.operation_3.setGeometry(QtCore.QRect(380, 150, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operation_3.setFont(font)
        self.operation_3.setObjectName(_fromUtf8("operation_3"))
        self.totalPayText = QtGui.QPlainTextEdit(self.payrollTab)
        self.totalPayText.setGeometry(QtCore.QRect(110, 220, 101, 31))
        self.totalPayText.setObjectName(_fromUtf8("totalPayText"))
        self.totalPayLabel = QtGui.QLabel(self.payrollTab)
        self.totalPayLabel.setGeometry(QtCore.QRect(130, 200, 101, 21))
        self.totalPayLabel.setObjectName(_fromUtf8("totalPayLabel"))
        self.money_5 = QtGui.QLabel(self.payrollTab)
        self.money_5.setGeometry(QtCore.QRect(100, 220, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.money_5.setFont(font)
        self.money_5.setObjectName(_fromUtf8("money_5"))
        self.calculateButton = QtGui.QPushButton(self.payrollTab)
        self.calculateButton.setGeometry(QtCore.QRect(210, 220, 101, 31))
        self.calculateButton.setObjectName(_fromUtf8("calculateButton"))

        self.tabs.addTab(self.payrollTab, _fromUtf8(""))
        self.emergencyContactTabl = QtGui.QWidget()
        self.emergencyContactTabl.setObjectName(_fromUtf8("emergencyContactTabl"))
        self.emergencyFNameLabel = QtGui.QLabel(self.emergencyContactTabl)
        self.emergencyFNameLabel.setGeometry(QtCore.QRect(130, 100, 61, 16))
        self.emergencyFNameLabel.setObjectName(_fromUtf8("emergencyFNameLabel"))
        self.emergencyLNameLabel = QtGui.QLabel(self.emergencyContactTabl)
        self.emergencyLNameLabel.setGeometry(QtCore.QRect(130, 160, 61, 16))
        self.emergencyLNameLabel.setObjectName(_fromUtf8("emergencyLNameLabel"))
        self.emergencyTitle = QtGui.QLabel(self.emergencyContactTabl)
        self.emergencyTitle.setGeometry(QtCore.QRect(150, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.emergencyTitle.setFont(font)
        self.emergencyTitle.setObjectName(_fromUtf8("emergencyTitle"))
        self.emergencyFNameText = QtGui.QPlainTextEdit(self.emergencyContactTabl)
        self.emergencyFNameText.setGeometry(QtCore.QRect(210, 100, 201, 31))
        self.emergencyFNameText.setObjectName(_fromUtf8("emergencyFNameText"))
        self.emergencyLNameText = QtGui.QPlainTextEdit(self.emergencyContactTabl)
        self.emergencyLNameText.setGeometry(QtCore.QRect(210, 160, 201, 31))
        self.emergencyLNameText.setObjectName(_fromUtf8("emergencyLNameText"))
        self.emergencyRelationshipLabel = QtGui.QLabel(self.emergencyContactTabl)
        self.emergencyRelationshipLabel.setGeometry(QtCore.QRect(130, 280, 71, 16))
        self.emergencyRelationshipLabel.setObjectName(_fromUtf8("emergencyRelationshipLabel"))
        self.comboBox_5 = QtGui.QComboBox(self.emergencyContactTabl)
        self.comboBox_5.setGeometry(QtCore.QRect(210, 280, 191, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.emergencyPhoneText = QtGui.QPlainTextEdit(self.emergencyContactTabl)
        self.emergencyPhoneText.setGeometry(QtCore.QRect(210, 220, 201, 31))
        self.emergencyPhoneText.setObjectName(_fromUtf8("emergencyPhoneText"))
        self.emergencyPhoneLabel = QtGui.QLabel(self.emergencyContactTabl)
        self.emergencyPhoneLabel.setGeometry(QtCore.QRect(130, 220, 81, 16))
        self.emergencyPhoneLabel.setObjectName(_fromUtf8("emergencyPhoneLabel"))
        self.emergencyEditButton = QtGui.QPushButton(self.emergencyContactTabl)
        self.emergencyEditButton.setGeometry(QtCore.QRect(130, 350, 75, 23))
        self.emergencyEditButton.setObjectName(_fromUtf8("emergencyEditButton"))
        self.emergencyUpdateButton = QtGui.QPushButton(self.emergencyContactTabl)
        self.emergencyUpdateButton.setGeometry(QtCore.QRect(240, 350, 75, 23))
        self.emergencyUpdateButton.setObjectName(_fromUtf8("emergencyUpdateButton"))
        self.emergencyCancelButton = QtGui.QPushButton(self.emergencyContactTabl)
        self.emergencyCancelButton.setGeometry(QtCore.QRect(350, 350, 75, 23))
        self.emergencyCancelButton.setObjectName(_fromUtf8("emergencyCancelButton"))
        self.tabs.addTab(self.emergencyContactTabl, _fromUtf8(""))
        self.addButton = QtGui.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(30, 500, 91, 23))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.deleteButton = QtGui.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(140, 500, 101, 23))
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.searchButton = QtGui.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(560, 10, 201, 51))
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        SimpleSaleCenterMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SimpleSaleCenterMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SimpleSaleCenterMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SimpleSaleCenterMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SimpleSaleCenterMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SimpleSaleCenterMainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimpleSaleCenterMainWindow)

        self.employeeTable.itemClicked.connect(self.demo)
        self.employeeTable.setCurrentCell(0,0)
        self.demo()
        QtCore.QObject.connect(self.workedDaysPButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.workedDaysP)
        QtCore.QObject.connect(self.workedDaysMButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.workedDaysM)
        QtCore.QObject.connect(self.sickDaysPButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sickDaysP)
        QtCore.QObject.connect(self.sickDaysMButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sickDaysM)
        QtCore.QObject.connect(self.overWorkPButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.overworkDaysP)
        QtCore.QObject.connect(self.overWorkMButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.overworkDaysM)
        QtCore.QObject.connect(self.vacationPButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vacationDaysP)
        QtCore.QObject.connect(self.vacationMButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vacationDaysM)
        QtCore.QObject.connect(self.editButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edit)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.cancel)
        QtCore.QObject.connect(self.updateButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.update)
        QtCore.QObject.connect(self.emergencyEditButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.eEdit)
        QtCore.QObject.connect(self.emergencyUpdateButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.eUpdate)
        QtCore.QObject.connect(self.emergencyCancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.eCancel)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.addEmployee)
        QtCore.QObject.connect(self.searchButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.saveEmployee)
        QtCore.QObject.connect(self.deleteButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.delEmployee)
        QtCore.QObject.connect(self.calculateButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.calculate)



    def retranslateUi(self, SimpleSaleCenterMainWindow):
        SimpleSaleCenterMainWindow.setWindowTitle(_translate("SimpleSaleCenterMainWindow", "MainWindow", None))
        self.listTitle.setText(_translate("SimpleSaleCenterMainWindow", "EMPLOYEE", None))
        #self.employeeTable.setSortingEnabled(True)
        item = self.employeeTable.verticalHeaderItem(0)
        item.setText(_translate("SimpleSaleCenterMainWindow", "1", None))
        item = self.employeeTable.verticalHeaderItem(1)
        item.setText(_translate("SimpleSaleCenterMainWindow", "2", None))
        item = self.employeeTable.verticalHeaderItem(2)
        item.setText(_translate("SimpleSaleCenterMainWindow", "3", None))
        item = self.employeeTable.verticalHeaderItem(3)
        item.setText(_translate("SimpleSaleCenterMainWindow", "4", None))
        item = self.employeeTable.verticalHeaderItem(4)
        item.setText(_translate("SimpleSaleCenterMainWindow", "5", None))
        item = self.employeeTable.verticalHeaderItem(5)
        item.setText(_translate("SimpleSaleCenterMainWindow", "6", None))
        item = self.employeeTable.verticalHeaderItem(6)
        item.setText(_translate("SimpleSaleCenterMainWindow", "7", None))
        item = self.employeeTable.verticalHeaderItem(7)
        item.setText(_translate("SimpleSaleCenterMainWindow", "8", None))
        item = self.employeeTable.verticalHeaderItem(8)
        item.setText(_translate("SimpleSaleCenterMainWindow", "9", None))
        item = self.employeeTable.verticalHeaderItem(9)
        item.setText(_translate("SimpleSaleCenterMainWindow", "10", None))
        item = self.employeeTable.verticalHeaderItem(10)
        item.setText(_translate("SimpleSaleCenterMainWindow", "11", None))
        item = self.employeeTable.verticalHeaderItem(11)
        item.setText(_translate("SimpleSaleCenterMainWindow", "12", None))
        item = self.employeeTable.verticalHeaderItem(12)
        item.setText(_translate("SimpleSaleCenterMainWindow", "13", None))
        item = self.employeeTable.verticalHeaderItem(13)
        item.setText(_translate("SimpleSaleCenterMainWindow", "14", None))
        item = self.employeeTable.verticalHeaderItem(14)
        item.setText(_translate("SimpleSaleCenterMainWindow", "15", None))
        item = self.employeeTable.verticalHeaderItem(15)
        item.setText(_translate("SimpleSaleCenterMainWindow", "16", None))
        item = self.employeeTable.verticalHeaderItem(16)
        item.setText(_translate("SimpleSaleCenterMainWindow", "17", None))
        item = self.employeeTable.verticalHeaderItem(17)
        item.setText(_translate("SimpleSaleCenterMainWindow", "18", None))
        item = self.employeeTable.verticalHeaderItem(18)
        item.setText(_translate("SimpleSaleCenterMainWindow", "19", None))
        item = self.employeeTable.verticalHeaderItem(19)
        item.setText(_translate("SimpleSaleCenterMainWindow", "20", None))
        item = self.employeeTable.verticalHeaderItem(20)
        item.setText(_translate("SimpleSaleCenterMainWindow", "21", None))
        item = self.employeeTable.verticalHeaderItem(21)
        item.setText(_translate("SimpleSaleCenterMainWindow", "22", None))
        item = self.employeeTable.verticalHeaderItem(22)
        item.setText(_translate("SimpleSaleCenterMainWindow", "23", None))
        item = self.employeeTable.verticalHeaderItem(23)
        item.setText(_translate("SimpleSaleCenterMainWindow", "24", None))
        item = self.employeeTable.verticalHeaderItem(24)
        item.setText(_translate("SimpleSaleCenterMainWindow", "25", None))
        item = self.employeeTable.verticalHeaderItem(25)
        item.setText(_translate("SimpleSaleCenterMainWindow", "26", None))
        item = self.employeeTable.verticalHeaderItem(26)
        item.setText(_translate("SimpleSaleCenterMainWindow", "27", None))
        item = self.employeeTable.verticalHeaderItem(27)
        item.setText(_translate("SimpleSaleCenterMainWindow", "28", None))
        item = self.employeeTable.verticalHeaderItem(28)
        item.setText(_translate("SimpleSaleCenterMainWindow", "29", None))
        item = self.employeeTable.verticalHeaderItem(29)
        item.setText(_translate("SimpleSaleCenterMainWindow", "30", None))
        item = self.employeeTable.verticalHeaderItem(30)
        item.setText(_translate("SimpleSaleCenterMainWindow", "31", None))
        item = self.employeeTable.verticalHeaderItem(31)
        item.setText(_translate("SimpleSaleCenterMainWindow", "32", None))
        item = self.employeeTable.verticalHeaderItem(32)
        item.setText(_translate("SimpleSaleCenterMainWindow", "33", None))
        item = self.employeeTable.verticalHeaderItem(33)
        item.setText(_translate("SimpleSaleCenterMainWindow", "34", None))
        item = self.employeeTable.verticalHeaderItem(34)
        item.setText(_translate("SimpleSaleCenterMainWindow", "35", None))
        item = self.employeeTable.verticalHeaderItem(35)
        item.setText(_translate("SimpleSaleCenterMainWindow", "36", None))
        item = self.employeeTable.verticalHeaderItem(36)
        item.setText(_translate("SimpleSaleCenterMainWindow", "37", None))
        item = self.employeeTable.verticalHeaderItem(37)
        item.setText(_translate("SimpleSaleCenterMainWindow", "38", None))
        item = self.employeeTable.verticalHeaderItem(38)
        item.setText(_translate("SimpleSaleCenterMainWindow", "39", None))
        item = self.employeeTable.verticalHeaderItem(39)
        item.setText(_translate("SimpleSaleCenterMainWindow", "40", None))
        item = self.employeeTable.verticalHeaderItem(40)
        item.setText(_translate("SimpleSaleCenterMainWindow", "41", None))
        item = self.employeeTable.verticalHeaderItem(41)
        item.setText(_translate("SimpleSaleCenterMainWindow", "42", None))
        item = self.employeeTable.verticalHeaderItem(42)
        item.setText(_translate("SimpleSaleCenterMainWindow", "43", None))
        item = self.employeeTable.verticalHeaderItem(43)
        item.setText(_translate("SimpleSaleCenterMainWindow", "44", None))
        item = self.employeeTable.verticalHeaderItem(44)
        item.setText(_translate("SimpleSaleCenterMainWindow", "45", None))
        item = self.employeeTable.verticalHeaderItem(45)
        item.setText(_translate("SimpleSaleCenterMainWindow", "46", None))
        item = self.employeeTable.verticalHeaderItem(46)
        item.setText(_translate("SimpleSaleCenterMainWindow", "47", None))
        item = self.employeeTable.verticalHeaderItem(47)
        item.setText(_translate("SimpleSaleCenterMainWindow", "48", None))
        item = self.employeeTable.verticalHeaderItem(48)
        item.setText(_translate("SimpleSaleCenterMainWindow", "49", None))
        item = self.employeeTable.verticalHeaderItem(49)
        item.setText(_translate("SimpleSaleCenterMainWindow", "50", None))
        item = self.employeeTable.verticalHeaderItem(50)
        item.setText(_translate("SimpleSaleCenterMainWindow", "51", None))
        item = self.employeeTable.verticalHeaderItem(51)
        item.setText(_translate("SimpleSaleCenterMainWindow", "52", None))
        item = self.employeeTable.verticalHeaderItem(52)
        item.setText(_translate("SimpleSaleCenterMainWindow", "53", None))
        item = self.employeeTable.verticalHeaderItem(53)
        item.setText(_translate("SimpleSaleCenterMainWindow", "54", None))
        item = self.employeeTable.verticalHeaderItem(54)
        item.setText(_translate("SimpleSaleCenterMainWindow", "55", None))
        item = self.employeeTable.verticalHeaderItem(55)
        item.setText(_translate("SimpleSaleCenterMainWindow", "56", None))
        item = self.employeeTable.verticalHeaderItem(56)
        item.setText(_translate("SimpleSaleCenterMainWindow", "57", None))
        item = self.employeeTable.verticalHeaderItem(57)
        item.setText(_translate("SimpleSaleCenterMainWindow", "58", None))
        item = self.employeeTable.verticalHeaderItem(58)
        item.setText(_translate("SimpleSaleCenterMainWindow", "59", None))
        item = self.employeeTable.verticalHeaderItem(59)
        item.setText(_translate("SimpleSaleCenterMainWindow", "60", None))
        item = self.employeeTable.verticalHeaderItem(60)
        item.setText(_translate("SimpleSaleCenterMainWindow", "61", None))
        item = self.employeeTable.verticalHeaderItem(61)
        item.setText(_translate("SimpleSaleCenterMainWindow", "62", None))
        item = self.employeeTable.verticalHeaderItem(62)
        item.setText(_translate("SimpleSaleCenterMainWindow", "63", None))
        item = self.employeeTable.verticalHeaderItem(63)
        item.setText(_translate("SimpleSaleCenterMainWindow", "64", None))
        item = self.employeeTable.verticalHeaderItem(64)
        item.setText(_translate("SimpleSaleCenterMainWindow", "65", None))
        item = self.employeeTable.verticalHeaderItem(65)
        item.setText(_translate("SimpleSaleCenterMainWindow", "66", None))
        item = self.employeeTable.verticalHeaderItem(66)
        item.setText(_translate("SimpleSaleCenterMainWindow", "67", None))
        item = self.employeeTable.verticalHeaderItem(67)
        item.setText(_translate("SimpleSaleCenterMainWindow", "68", None))
        item = self.employeeTable.verticalHeaderItem(68)
        item.setText(_translate("SimpleSaleCenterMainWindow", "69", None))
        item = self.employeeTable.verticalHeaderItem(69)
        item.setText(_translate("SimpleSaleCenterMainWindow", "70", None))
        item = self.employeeTable.verticalHeaderItem(70)
        item.setText(_translate("SimpleSaleCenterMainWindow", "71", None))
        item = self.employeeTable.verticalHeaderItem(71)
        item.setText(_translate("SimpleSaleCenterMainWindow", "72", None))
        item = self.employeeTable.verticalHeaderItem(72)
        item.setText(_translate("SimpleSaleCenterMainWindow", "73", None))
        item = self.employeeTable.verticalHeaderItem(73)
        item.setText(_translate("SimpleSaleCenterMainWindow", "74", None))
        item = self.employeeTable.verticalHeaderItem(74)
        item.setText(_translate("SimpleSaleCenterMainWindow", "75", None))
        item = self.employeeTable.verticalHeaderItem(75)
        item.setText(_translate("SimpleSaleCenterMainWindow", "76", None))
        item = self.employeeTable.verticalHeaderItem(76)
        item.setText(_translate("SimpleSaleCenterMainWindow", "77", None))
        item = self.employeeTable.verticalHeaderItem(77)
        item.setText(_translate("SimpleSaleCenterMainWindow", "78", None))
        item = self.employeeTable.verticalHeaderItem(78)
        item.setText(_translate("SimpleSaleCenterMainWindow", "79", None))
        item = self.employeeTable.verticalHeaderItem(79)
        item.setText(_translate("SimpleSaleCenterMainWindow", "80", None))
        item = self.employeeTable.verticalHeaderItem(80)
        item.setText(_translate("SimpleSaleCenterMainWindow", "81", None))
        item = self.employeeTable.verticalHeaderItem(81)
        item.setText(_translate("SimpleSaleCenterMainWindow", "82", None))
        item = self.employeeTable.verticalHeaderItem(82)
        item.setText(_translate("SimpleSaleCenterMainWindow", "83", None))
        item = self.employeeTable.verticalHeaderItem(83)
        item.setText(_translate("SimpleSaleCenterMainWindow", "84", None))
        item = self.employeeTable.verticalHeaderItem(84)
        item.setText(_translate("SimpleSaleCenterMainWindow", "85", None))
        item = self.employeeTable.verticalHeaderItem(85)
        item.setText(_translate("SimpleSaleCenterMainWindow", "86", None))
        item = self.employeeTable.verticalHeaderItem(86)
        item.setText(_translate("SimpleSaleCenterMainWindow", "87", None))
        item = self.employeeTable.verticalHeaderItem(87)
        item.setText(_translate("SimpleSaleCenterMainWindow", "88", None))
        item = self.employeeTable.verticalHeaderItem(88)
        item.setText(_translate("SimpleSaleCenterMainWindow", "89", None))
        item = self.employeeTable.verticalHeaderItem(89)
        item.setText(_translate("SimpleSaleCenterMainWindow", "90", None))
        item = self.employeeTable.verticalHeaderItem(90)
        item.setText(_translate("SimpleSaleCenterMainWindow", "91", None))
        item = self.employeeTable.verticalHeaderItem(91)
        item.setText(_translate("SimpleSaleCenterMainWindow", "92", None))
        item = self.employeeTable.verticalHeaderItem(92)
        item.setText(_translate("SimpleSaleCenterMainWindow", "93", None))
        item = self.employeeTable.verticalHeaderItem(93)
        item.setText(_translate("SimpleSaleCenterMainWindow", "94", None))
        item = self.employeeTable.verticalHeaderItem(94)
        item.setText(_translate("SimpleSaleCenterMainWindow", "95", None))
        item = self.employeeTable.verticalHeaderItem(95)
        item.setText(_translate("SimpleSaleCenterMainWindow", "96", None))
        item = self.employeeTable.verticalHeaderItem(96)
        item.setText(_translate("SimpleSaleCenterMainWindow", "97", None))
        item = self.employeeTable.verticalHeaderItem(97)
        item.setText(_translate("SimpleSaleCenterMainWindow", "98", None))
        item = self.employeeTable.verticalHeaderItem(98)
        item.setText(_translate("SimpleSaleCenterMainWindow", "99", None))
        item = self.employeeTable.verticalHeaderItem(99)
        item.setText(_translate("SimpleSaleCenterMainWindow", "100", None))
        item = self.employeeTable.horizontalHeaderItem(0)
        item.setText(_translate("SimpleSaleCenterMainWindow", "EMPLOYEE ID", None))
        item = self.employeeTable.horizontalHeaderItem(1)
        item.setText(_translate("SimpleSaleCenterMainWindow", "NAME", None))
        self.mainTitle.setText(_translate("SimpleSaleCenterMainWindow", "Simple Sales Centre", None))
        self.genderLabel.setText(_translate("SimpleSaleCenterMainWindow", "Gender:", None))
        self.cellPhoneLabel.setText(_translate("SimpleSaleCenterMainWindow", "Cell Phone:", None))
        self.lNameLab.setText(_translate("SimpleSaleCenterMainWindow", "Last Name:", None))
        self.homePhoneLabel.setText(_translate("SimpleSaleCenterMainWindow", "Home Phone:", None))
        self.marriedBox.setItemText(0, _translate("SimpleSaleCenterMainWindow", "Single", None))
        self.marriedBox.setItemText(1, _translate("SimpleSaleCenterMainWindow", "Married", None))
        self.marriedBox.setItemText(2, _translate("SimpleSaleCenterMainWindow", "Other", None))
        self.cancelButton.setText(_translate("SimpleSaleCenterMainWindow", "Cancel", None))
        self.addressLabel.setText(_translate("SimpleSaleCenterMainWindow", "Address:", None))
        self.degreeBox.setItemText(0, _translate("SimpleSaleCenterMainWindow", "Advanced Degree", None))
        self.degreeBox.setItemText(1, _translate("SimpleSaleCenterMainWindow", "Bachelor\'s Degree", None))
        self.degreeBox.setItemText(2, _translate("SimpleSaleCenterMainWindow", "High School Disploma", None))
        self.degreeBox.setItemText(3, _translate("SimpleSaleCenterMainWindow", "Other", None))
        self.startDateLabel.setText(_translate("SimpleSaleCenterMainWindow", "Work Start Date:", None))
        self.idLabel.setText(_translate("SimpleSaleCenterMainWindow", "Employee ID# :", None))
        self.managerLabel.setText(_translate("SimpleSaleCenterMainWindow", "Manager Name:", None))
        self.marriedLabel.setText(_translate("SimpleSaleCenterMainWindow", "Marital Status:", None))
        self.sinLabel.setText(_translate("SimpleSaleCenterMainWindow", "SIN # :", None))
        self.jobLabel.setText(_translate("SimpleSaleCenterMainWindow", "Job Position:", None))
        self.genderF.setText(_translate("SimpleSaleCenterMainWindow", "FEMALE", None))
        self.emailLabel.setText(_translate("SimpleSaleCenterMainWindow", "Email:", None))
        self.departLabel.setText(_translate("SimpleSaleCenterMainWindow", "Department:", None))
        self.fNameLabel.setText(_translate("SimpleSaleCenterMainWindow", "First Name:", None))
        self.genderO.setText(_translate("SimpleSaleCenterMainWindow", "OTHER", None))
        self.genderM.setText(_translate("SimpleSaleCenterMainWindow", "MALE", None))
        self.bDateLabel.setText(_translate("SimpleSaleCenterMainWindow", "Date Of Birth (YYYYMMDD):", None))
        self.degreeLabel.setText(_translate("SimpleSaleCenterMainWindow", "Education:", None))
        self.workPhoneLabel.setText(_translate("SimpleSaleCenterMainWindow", "Work Phone:", None))
        self.editButton.setText(_translate("SimpleSaleCenterMainWindow", "Edit", None))
        self.updateButton.setText(_translate("SimpleSaleCenterMainWindow", "Update", None))
        self.salaryPayRateLabel.setText(_translate("SimpleSaleCenterMainWindow", "Salary/Pay Rate:", None))
        self.tabs.setTabText(self.tabs.indexOf(self.generalTab), _translate("SimpleSaleCenterMainWindow", "GENERAL", None))
        self.workedDaysLabel.setText(_translate("SimpleSaleCenterMainWindow", "Days Worked:", None))
        self.sickDaysLabel.setText(_translate("SimpleSaleCenterMainWindow", "Sick Days:", None))
        self.vacationLabel.setText(_translate("SimpleSaleCenterMainWindow", "Vacation Days:", None))
        self.workedDaysPButton.setText(_translate("SimpleSaleCenterMainWindow", "+", None))
        self.workedDaysMButton.setText(_translate("SimpleSaleCenterMainWindow", "-", None))
        self.sickDaysPButton.setText(_translate("SimpleSaleCenterMainWindow", "+", None))
        self.sickDaysMButton.setText(_translate("SimpleSaleCenterMainWindow", "-", None))
        self.vacationPButton.setText(_translate("SimpleSaleCenterMainWindow", "+", None))
        self.vacationMButton.setText(_translate("SimpleSaleCenterMainWindow", "-", None))
        self.availableVacationLabel.setText(_translate("SimpleSaleCenterMainWindow", "Available Days of Vacation:", None))
        self.overWorkPButton.setText(_translate("SimpleSaleCenterMainWindow", "+", None))
        self.overWorkLabel.setText(_translate("SimpleSaleCenterMainWindow", "Overtime Working Hours:", None))
        self.overWorkMButton.setText(_translate("SimpleSaleCenterMainWindow", "-", None))
        self.tabs.setTabText(self.tabs.indexOf(self.attendanceTab), _translate("SimpleSaleCenterMainWindow", "ATTENDANCE", None))
        self.generalPayLabel.setText(_translate("SimpleSaleCenterMainWindow", "General Pay:", None))
        self.bonusLabel.setText(_translate("SimpleSaleCenterMainWindow", "Bonus:", None))
        self.deductionLabel.setText(_translate("SimpleSaleCenterMainWindow", "Deduction:", None))
        self.money_1.setText(_translate("SimpleSaleCenterMainWindow", "$", None))
        self.money_3.setText(_translate("SimpleSaleCenterMainWindow", "$", None))
        self.money_4.setText(_translate("SimpleSaleCenterMainWindow", "$", None))

        self.totalSign.setText(_translate("SimpleSaleCenterMainWindow", "=", None))


        self.operation_2.setText(_translate("SimpleSaleCenterMainWindow", "+", None))
        self.operation_3.setText(_translate("SimpleSaleCenterMainWindow", "-", None))
        self.totalPayLabel.setText(_translate("SimpleSaleCenterMainWindow", "Total Pay:", None))
        self.money_5.setText(_translate("SimpleSaleCenterMainWindow", "$", None))
        self.calculateButton.setText(_translate("SimpleSaleCenterMainWindow", "Calculate", None))
        self.tabs.setTabText(self.tabs.indexOf(self.payrollTab), _translate("SimpleSaleCenterMainWindow", "PAYROLL", None))
        self.emergencyFNameLabel.setText(_translate("SimpleSaleCenterMainWindow", "First Name:", None))
        self.emergencyLNameLabel.setText(_translate("SimpleSaleCenterMainWindow", "Last Name:", None))
        self.emergencyTitle.setText(_translate("SimpleSaleCenterMainWindow", "Emergency Contact:", None))
        self.emergencyRelationshipLabel.setText(_translate("SimpleSaleCenterMainWindow", "Relationship:", None))
        self.comboBox_5.setItemText(0, _translate("SimpleSaleCenterMainWindow", "Family", None))
        self.comboBox_5.setItemText(1, _translate("SimpleSaleCenterMainWindow", "Friend", None))
        self.comboBox_5.setItemText(2, _translate("SimpleSaleCenterMainWindow", "Employee", None))
        self.comboBox_5.setItemText(3, _translate("SimpleSaleCenterMainWindow", "Employer", None))
        self.comboBox_5.setItemText(4, _translate("SimpleSaleCenterMainWindow", "Neighbour", None))
        self.emergencyPhoneLabel.setText(_translate("SimpleSaleCenterMainWindow", "Phone Number:", None))
        self.emergencyEditButton.setText(_translate("SimpleSaleCenterMainWindow", "Edit", None))
        self.emergencyUpdateButton.setText(_translate("SimpleSaleCenterMainWindow", "Update", None))
        self.emergencyCancelButton.setText(_translate("SimpleSaleCenterMainWindow", "Cancel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.emergencyContactTabl), _translate("SimpleSaleCenterMainWindow", "EMERGENCY ", None))
        self.addButton.setText(_translate("SimpleSaleCenterMainWindow", "Add Employee", None))
        self.deleteButton.setText(_translate("SimpleSaleCenterMainWindow", "Delete Employee", None))
        self.searchButton.setText(_translate("SimpleSaleCenterMainWindow", "SAVE", None))
        for x in range(len(employeeList)):
            self.employeeTable
            self.employeeTable.setItem(x,0,QtGui.QTableWidgetItem(str(employeeList[x].GetEmployeeID())))
            self.employeeTable.setItem(x,1,QtGui.QTableWidgetItem(str(employeeList[x].GetLastName()+", "+employeeList[x].GetFirstName())))

        self.searchButton.setEnabled(False)

        self.fNameText.setEnabled(False)
        self.lNameText.setEnabled(False)
        self.genderM.setEnabled(False)
        self.genderF.setEnabled(False)
        self.genderO.setEnabled(False)
        self.marriedBox.setEnabled(False)
        self.bDateText.setEnabled(False)
        self.idText.setEnabled(False)
        self.sinText.setEnabled(False)
        self.departText.setEnabled(False)
        self.jobText.setEnabled(False)
        self.managerText.setEnabled(False)
        self.salaryPayRateText.setEnabled(False)
        self.addressText.setEnabled(False)
        self.degreeBox.setEnabled(False)
        self.startDateText.setEnabled(False)
        self.homePhoneText.setEnabled(False)
        self.workPhoneText.setEnabled(False)
        self.cellPhoneText.setEnabled(False)
        self.emailText.setEnabled(False)
        self.updateButton.setEnabled(False)
        self.cancelButton.setEnabled(False)
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)

        self.workedDaysText.setEnabled(False)
        self.overWorkText.setEnabled(False)
        self.sickDaysText.setEnabled(False)
        self.vacationText.setEnabled(False)
        self.availableVacationText.setEnabled(False)

        self.emergencyFNameText.setEnabled(False)
        self.emergencyLNameText.setEnabled(False)
        self.emergencyPhoneText.setEnabled(False)
        self.comboBox_5.setEnabled(False)

    def demo(self):
        self.fNameText.setPlainText(employeeList[self.employeeTable.currentRow()].GetFirstName())
        self.lNameText.setPlainText(employeeList[self.employeeTable.currentRow()].GetLastName())
        self.bDateText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetBirthDate()))
        self.idText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetEmployeeID()))
        self.sinText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetSINNumber()))
        self.departText.setPlainText(employeeList[self.employeeTable.currentRow()].GetDepartment())
        self.jobText.setPlainText(employeeList[self.employeeTable.currentRow()].GetJobTitle())
        self.managerText.setPlainText(employeeList[self.employeeTable.currentRow()].GetManagerName())
        self.salaryPayRateText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetPayroll()))
        self.addressText.setPlainText(employeeList[self.employeeTable.currentRow()].GetAddress())

        self.startDateText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetStartDate()))
        self.homePhoneText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetHomePhone()))
        self.workPhoneText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetWorkPhone()))
        self.cellPhoneText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetWorkPhone()))
        self.emailText.setPlainText(employeeList[self.employeeTable.currentRow()].GetEmail())

        if employeeList[self.employeeTable.currentRow()].GetGender()=="Male":
            self.genderM.setChecked(True)
        elif employeeList[self.employeeTable.currentRow()].GetGender()=="Female":
            self.genderF.setChecked(True)
        elif employeeList[self.employeeTable.currentRow()].GetGender()=="Other":
            self.genderO.setChecked(True)

        if employeeList[self.employeeTable.currentRow()].GetMaritalStatus()=="Single":
            self.marriedBox.setCurrentIndex(0)
        elif employeeList[self.employeeTable.currentRow()].GetMaritalStatus()=="Married":
            self.marriedBox.setCurrentIndex(1)
        elif employeeList[self.employeeTable.currentRow()].GetMaritalStatus()=="Other":
            self.marriedBox.setCurrentIndex(2)

        if employeeList[self.employeeTable.currentRow()].GetEducation()=="Advanced Degree":
            self.degreeBox.setCurrentIndex(0)
        elif employeeList[self.employeeTable.currentRow()].GetEducation()=="Bachelor's Degree":
            self.degreeBox.setCurrentIndex(1)
        elif employeeList[self.employeeTable.currentRow()].GetEducation()=="High School Diploma":
            self.degreeBox.setCurrentIndex(2)
        elif employeeList[self.employeeTable.currentRow()].GetEducation()=="Other":
            self.degreeBox.setCurrentIndex(3)

        self.generalPayText.setPlainText(str(round(employeeList[self.employeeTable.currentRow()].Pay(employeeList[self.employeeTable.currentRow()].GetNumDaysWorked(),employeeList[self.employeeTable.currentRow()].GetOvertimeHours()),2)))
        self.bonusText.setPlainText("0")
        self.deductionText.setPlainText("0")

        self.workedDaysText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetNumDaysWorked()))
        self.overWorkText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetOvertimeHours()))
        self.sickDaysText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetNumSickDaysTaken()))
        self.vacationText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetNumVacationDaysTaken()))
        self.availableVacationText.setPlainText(str(employeeList[self.employeeTable.currentRow()].GetNumVacationDaysAvilable()))



        self.emergencyFNameText.setPlainText(employeeList[self.employeeTable.currentRow()].GetEmergencyFirstName())
        self.emergencyLNameText.setPlainText(employeeList[self.employeeTable.currentRow()].GetEmergencyLastName())
        self.emergencyPhoneText.setPlainText(employeeList[self.employeeTable.currentRow()].GetEmergencyPhoneNumber())

        if employeeList[self.employeeTable.currentRow()].GetEmergencyRelationship()=="Family":
            self.comboBox_5.setCurrentIndex(0)
        elif employeeList[self.employeeTable.currentRow()].GetEmergencyRelationship()=="Friend":
            self.comboBox_5.setCurrentIndex(1)
        elif employeeList[self.employeeTable.currentRow()].GetEmergencyRelationship()=="Employee":
            self.comboBox_5.setCurrentIndex(2)
        elif employeeList[self.employeeTable.currentRow()].GetEmergencyRelationship()=="Employer":
            self.comboBox_5.setCurrentIndex(3)
        elif employeeList[self.employeeTable.currentRow()].GetEmergencyRelationship()=="Neighbour":
            self.comboBox_5.setCurrentIndex(4)

    def workedDaysP(self):
        self.workedDaysText.setPlainText(str(int(self.workedDaysText.toPlainText())+1))
        self.save()
    def workedDaysM(self):
        if int(self.workedDaysText.toPlainText())>0:
            self.workedDaysText.setPlainText(str(int(self.workedDaysText.toPlainText())-1))
        self.save()
    def sickDaysP(self):
        self.sickDaysText.setPlainText(str(int(self.sickDaysText.toPlainText())+1))
        self.save()
    def sickDaysM(self):
        if int(self.sickDaysText.toPlainText())>0:
            self.sickDaysText.setPlainText(str(int(self.sickDaysText.toPlainText())-1))
        self.save()
    def overworkDaysP(self):
        self.overWorkText.setPlainText(str(int(self.overWorkText.toPlainText())+1))
        self.save()
    def overworkDaysM(self):
        if int(self.overWorkText.toPlainText())>0:
            self.overWorkText.setPlainText(str(int(self.overWorkText.toPlainText())-1))
        self.save()
    def vacationDaysP(self):
        self.vacationText.setPlainText(str(int(self.vacationText.toPlainText())+1))
        self.save()
    def vacationDaysM(self):
        if int(self.vacationText.toPlainText())>0:
            self.vacationText.setPlainText(str(int(self.vacationText.toPlainText())-1))
        self.save()
    def edit(self):
        self.fNameText.setEnabled(True)
        self.lNameText.setEnabled(True)
        self.genderM.setEnabled(True)
        self.genderF.setEnabled(True)
        self.genderO.setEnabled(True)
        self.marriedBox.setEnabled(True)
        self.bDateText.setEnabled(True)
        self.idText.setEnabled(True)
        self.sinText.setEnabled(True)
        self.departText.setEnabled(True)
        self.jobText.setEnabled(True)
        self.managerText.setEnabled(True)
        self.salaryPayRateText.setEnabled(True)
        self.addressText.setEnabled(True)
        self.degreeBox.setEnabled(True)
        self.startDateText.setEnabled(True)
        self.homePhoneText.setEnabled(True)
        self.workPhoneText.setEnabled(True)
        self.cellPhoneText.setEnabled(True)
        self.emailText.setEnabled(True)
        self.updateButton.setEnabled(True)
        self.cancelButton.setEnabled(True)
        self.emergencyUpdateButton.setEnabled(True)
        self.emergencyCancelButton.setEnabled(True)
        self.editButton.setEnabled(False)

    def cancel(self):
        self.fNameText.setEnabled(False)
        self.lNameText.setEnabled(False)
        self.genderM.setEnabled(False)
        self.genderF.setEnabled(False)
        self.genderO.setEnabled(False)
        self.marriedBox.setEnabled(False)
        self.bDateText.setEnabled(False)
        self.idText.setEnabled(False)
        self.sinText.setEnabled(False)
        self.departText.setEnabled(False)
        self.jobText.setEnabled(False)
        self.managerText.setEnabled(False)
        self.salaryPayRateText.setEnabled(False)
        self.addressText.setEnabled(False)
        self.degreeBox.setEnabled(False)
        self.startDateText.setEnabled(False)
        self.homePhoneText.setEnabled(False)
        self.workPhoneText.setEnabled(False)
        self.cellPhoneText.setEnabled(False)
        self.emailText.setEnabled(False)
        self.updateButton.setEnabled(False)
        self.cancelButton.setEnabled(False)
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)
        self.searchButton.setEnabled(False)
        self.editButton.setEnabled(True)
        self.eCancel()
        self.demo()

    def update(self):
        self.fNameText.setEnabled(False)
        self.lNameText.setEnabled(False)
        self.genderM.setEnabled(False)
        self.genderF.setEnabled(False)
        self.genderO.setEnabled(False)
        self.marriedBox.setEnabled(False)
        self.bDateText.setEnabled(False)
        self.idText.setEnabled(False)
        self.sinText.setEnabled(False)
        self.departText.setEnabled(False)
        self.jobText.setEnabled(False)
        self.managerText.setEnabled(False)
        self.salaryPayRateText.setEnabled(False)
        self.addressText.setEnabled(False)
        self.degreeBox.setEnabled(False)
        self.startDateText.setEnabled(False)
        self.homePhoneText.setEnabled(False)
        self.workPhoneText.setEnabled(False)
        self.cellPhoneText.setEnabled(False)
        self.emailText.setEnabled(False)
        self.updateButton.setEnabled(False)
        self.cancelButton.setEnabled(False)
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)
        self.editButton.setEnabled(True)
        self.save()
    def eEdit(self):
        self.emergencyFNameText.setEnabled(True)
        self.emergencyLNameText.setEnabled(True)
        self.emergencyPhoneText.setEnabled(True)
        self.comboBox_5.setEnabled(True)
        self.emergencyUpdateButton.setEnabled(True)
        self.emergencyCancelButton.setEnabled(True)
        self.emergencyEditButton.setEnabled(False)
    def eCancel(self):
        self.emergencyFNameText.setEnabled(False)
        self.emergencyLNameText.setEnabled(False)
        self.emergencyPhoneText.setEnabled(False)
        self.comboBox_5.setEnabled(False)
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)
        self.emergencyEditButton.setEnabled(True)
        self.demo()
    def eUpdate(self):
        self.emergencyFNameText.setEnabled(False)
        self.emergencyLNameText.setEnabled(False)
        self.emergencyPhoneText.setEnabled(False)
        self.comboBox_5.setEnabled(False)
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)
        self.emergencyEditButton.setEnabled(True)
        self.save()
    def addEmployee(self):
        self.employeeTable.setCurrentCell(0,0)
        self.fNameText.setPlainText("")
        self.lNameText.setPlainText("")
        self.bDateText.setPlainText("")
        self.idText.setPlainText("")
        self.sinText.setPlainText("")
        self.departText.setPlainText("")
        self.jobText.setPlainText("")
        self.managerText.setPlainText("")
        self.salaryPayRateText.setPlainText("")
        self.addressText.setPlainText("")

        self.startDateText.setPlainText("")
        self.homePhoneText.setPlainText("")
        self.workPhoneText.setPlainText("")
        self.cellPhoneText.setPlainText("")
        self.emailText.setPlainText("")

        self.genderM.setChecked(True)
        self.marriedBox.setCurrentIndex(0)
        self.degreeBox.setCurrentIndex(0)

        self.workedDaysText.setPlainText("0")
        self.overWorkText.setPlainText("0")
        self.sickDaysText.setPlainText("0")
        self.vacationText.setPlainText("0")
        self.availableVacationText.setPlainText("0")

        self.emergencyFNameText.setPlainText("")
        self.emergencyLNameText.setPlainText("")
        self.emergencyPhoneText.setPlainText("")
        self.comboBox_5.setCurrentIndex(0)
        self.edit()
        self.updateButton.setEnabled(False)
        self.searchButton.setEnabled(True)
        self.eEdit()
        self.emergencyUpdateButton.setEnabled(False)
        self.emergencyCancelButton.setEnabled(False)
        self.idText.setEnabled(False)
    def save(self):
        employeeList[self.employeeTable.currentRow()].SetFirstName(self.fNameText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetLastName(self.lNameText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetBirthDate(int(self.bDateText.toPlainText()))
        employeeList[self.employeeTable.currentRow()].SetSINNumber(int(self.sinText.toPlainText()))
        employeeList[self.employeeTable.currentRow()].SetDepartment(self.departText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetJobTitle(self.jobText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetManagerName(self.jobText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetPayroll(self.salaryPayRateText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetAddress(self.addressText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetStartDate(self.startDateText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetHomePhone(self.homePhoneText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetWorkPhone(self.workPhoneText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetEmail(self.emailText.toPlainText())
        if self.genderM.isChecked():
            employeeList[self.employeeTable.currentRow()].SetGender("Male")
        elif self.genderF.isChecked():
            employeeList[self.employeeTable.currentRow()].SetGender("Female")
        elif self.genderO.isChecked():
            employeeList[self.employeeTable.currentRow()].SetGender("Other")

        if self.marriedBox.currentIndex()==0:
            employeeList[self.employeeTable.currentRow()].SetMaritalStatus("Single")
        elif self.marriedBox.currentIndex()==1:
            employeeList[self.employeeTable.currentRow()].SetMaritalStatus("Married")
        elif self.marriedBox.currentIndex()==2:
            employeeList[self.employeeTable.currentRow()].SetMaritalStatus("Other")

        if self.degreeBox.currentIndex()==0:
            employeeList[self.employeeTable.currentRow()].SetEducation("Advanced Degree")
        elif self.degreeBox.currentIndex()==1:
            employeeList[self.employeeTable.currentRow()].SetEducation("Bachelor's Degree")
        elif self.degreeBox.currentIndex()==2:
            employeeList[self.employeeTable.currentRow()].SetEducation("High School Diploma")
        elif self.degreeBox.currentIndex()==3:
            employeeList[self.employeeTable.currentRow()].SetEducation("Other")

        employeeList[self.employeeTable.currentRow()].SetNumDaysWorked(self.workedDaysText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetOvertimeHours(self.overWorkText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetNumSickDaysTaken(self.sickDaysText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetNumVacationDaysTaken(self.vacationText.toPlainText())

        employeeList[self.employeeTable.currentRow()].SetEmergencyFirstName(self.emergencyFNameText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetEmergencyLastName(self.emergencyLNameText.toPlainText())
        employeeList[self.employeeTable.currentRow()].SetEmergencyNumber(self.emergencyPhoneText.toPlainText())

        if self.comboBox_5.currentIndex()==0:
            employeeList[self.employeeTable.currentRow()].SetEmergencyRelationship("Family")
        elif self.comboBox_5.currentIndex()==1:
            employeeList[self.employeeTable.currentRow()].SetEmergencyRelationship("Friend")
        elif self.comboBox_5.currentIndex()==2:
            employeeList[self.employeeTable.currentRow()].SetEmergencyRelationship("Employee")
        elif self.comboBox_5.currentIndex()==3:
            employeeList[self.employeeTable.currentRow()].SetEmergencyRelationship("Employeer")
        elif self.comboBox_5.currentIndex()==4:
            employeeList[self.employeeTable.currentRow()].SetEmergencyRelationship("Neighbour")


        if self.jobText.toPlainText()!=employeeList[self.employeeTable.currentRow()].GetJobTitle():
            if self.jobText.toPlainText()=="Associate":
                toManager(self.employeeTable.currentRow())
            else:
                toAssociate(self.employeeTable.currentRow())
        if employeeList[self.employeeTable.currentRow()].GetJobTitle()=="Manager":
                employeeList[self.employeeTable.currentRow()].SetPaytype("Salary")
        else:
                employeeList[self.employeeTable.currentRow()].SetPaytype("Wage")

        saveEverything()
        for x in range(len(employeeList)):
            self.employeeTable
            self.employeeTable.setItem(x,0,QtGui.QTableWidgetItem(str(employeeList[x].GetEmployeeID())))
            self.employeeTable.setItem(x,1,QtGui.QTableWidgetItem(str(employeeList[x].GetLastName()+", "+employeeList[x].GetFirstName())))
        self.employeeTable.setCurrentCell(self.employeeTable.currentRow(),0)
        self.cancel()
    def saveEmployee(self):
        self.fNameText.toPlainText()
        a=self.jobText.toPlainText()
        c=self.departText.toPlainText()
        d=self.fNameText.toPlainText()
        e=self.lNameText.toPlainText()
        if self.genderM.isChecked():
            f="Male"
        elif self.genderF.isChecked():
            f="Female"
        elif self.genderO.isChecked():
            f="Other"
        g=self.bDateText.toPlainText()
        i=self.sinText.toPlainText()
        h=self.salaryPayRateText.toPlainText()
        if self.marriedBox.currentIndex()==0:
            j="Single"
        elif self.marriedBox.currentIndex()==1:
            j="Married"
        elif self.marriedBox.currentIndex()==2:
            j="other"
        k=self.homePhoneText.toPlainText()
        l=self.workPhoneText.toPlainText()
        m=self.addressText.toPlainText()
        n=self.managerText.toPlainText()
        if self.degreeBox.currentIndex()==0:
            o="Advanced Degree"
        elif self.degreeBox.currentIndex()==1:
            o="Bachelor's Degree"
        elif self.degreeBox.currentIndex()==2:
            o="High School Diploma"
        elif self.degreeBox.currentIndex()==3:
            o="Other"
        p=self.startDateText.toPlainText()
        q=self.emailText.toPlainText()
        r=self.emergencyFNameText.toPlainText()
        s=self.emergencyLNameText.toPlainText()
        if self.comboBox_5.currentIndex()==0:
            t="Family"
        elif self.comboBox_5.currentIndex()==1:
            t="Friend"
        elif self.comboBox_5.currentIndex()==2:
            t="Employee"
        elif self.comboBox_5.currentIndex()==3:
            t="Employeer"
        elif self.comboBox_5.currentIndex()==4:
            t="Neighbour"
        u=self.emergencyPhoneText.toPlainText()
        v="0"
        w="0"
        x="0"
        y="0"
        z="0"
        newEmployee(a,     c, d, e, f, g, i, h, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z)
        saveEverything()
        for x in range(len(employeeList)):
            self.employeeTable
            self.employeeTable.setItem(x,0,QtGui.QTableWidgetItem(str(employeeList[x].GetEmployeeID())))
            self.employeeTable.setItem(x,1,QtGui.QTableWidgetItem(str(employeeList[x].GetLastName()+", "+employeeList[x].GetFirstName())))
        self.employeeTable.setCurrentCell(self.employeeTable.currentRow(),0)
        self.cancel()
    def delEmployee(self):
        deleteEmployee(employeeList[self.employeeTable.currentRow()].GetEmployeeID())
        saveEverything()
        for x in range(len(employeeList)+1):
            if x<len(employeeList):
                self.employeeTable.setItem(x,0,QtGui.QTableWidgetItem(str(employeeList[x].GetEmployeeID())))
                self.employeeTable.setItem(x,1,QtGui.QTableWidgetItem(str(employeeList[x].GetLastName()+", "+employeeList[x].GetFirstName())))
            else:
                self.employeeTable.setItem(x,0,QtGui.QTableWidgetItem(""))
                self.employeeTable.setItem(x,1,QtGui.QTableWidgetItem(""))

        self.employeeTable.setCurrentCell(0,0)
        self.cancel()
    def calculate(self):
         gen=employeeList[self.employeeTable.currentRow()].Pay(employeeList[self.employeeTable.currentRow()].GetNumDaysWorked(),employeeList[self.employeeTable.currentRow()].GetOvertimeHours())
         bon=float(self.bonusText.toPlainText())
         ded=float(self.deductionText.toPlainText())
         total=round(gen+bon-ded,2)
         self.totalPayText.setPlainText(str(total))

if __name__=="__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FrameS = QtGui.QMainWindow()     #Frame gets functions/attributes from the QtGui
    uiS = Ui_SearchWindow()      #Connects the interface with the 'Ui_SearchWindow'
    uiS.setupUi(FrameS)       #Sets up the user interface according to the frame
    FrameS.show()        #Shows the graphic user interface
    Frame = QtGui.QMainWindow()
    ui = Ui_SimpleSaleCenterMainWindow()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())